pypro/aperitivos/urls.py
from django.urls import path

from pypro.aperitivos.views import video

app_name='aperitivos'
urlpatterns = [
    path('<slug:slug>', video, name='video'),
]

pypro/base/urls.py
from django.urls import path

from pypro.base.views import home

app_name='base'
urlpatterns = [
    path('', home, name='home'),
]

pypro/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

#from pypro import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pypro.base.urls')),
    path('aperitivos/', include('pypro.aperitivos.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns.append(
        path('__debug__/', include(debug_toolbar.urls))
    )

pypro/base/models.py
from django.db import models
from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
from django.contrib.auth.models import PermissionsMixin
from django.utils.translation import gettext_lazy as _
from django.utils import timezone
from django.core.mail import send_mail

class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """
        Create and save a user with the given username, email, and password.
        """
        if not email:
            raise ValueError("The given email must be set")
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user


    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault("is_superuser", False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault("is_superuser", True)
        extra_fields.setdefault("is_staff", True)

        if extra_fields.get("is_superuser") is not True:
            raise ValueError("Superuser must have is_superuser=True.")
        if extra_fields.get("is_staff") is not True:
            raise ValueError("Superuser must have is_staff=True.")

        return self._create_user(email, password, **extra_fields)

class User(AbstractBaseUser, PermissionsMixin):
    """
    An abstract base class implementing a fully featured User model with
    admin-compliant permissions.

    Username and password are required. Other fields are optional.
    """

    first_name = models.CharField(_("first name"), max_length=150, blank=True)
    email = models.EmailField(_("email address"), unique=True)
    is_staff = models.BooleanField(
        _("staff status"),
        default=False,
        help_text=_("Designates whether the user can log into this admin site."),
    )
    is_active = models.BooleanField(
        _("active"),
        default=True,
        help_text=_(
            "Designates whether this user should be treated as active. "
            "Unselect this instead of deleting accounts."
        ),
    )
    date_joined = models.DateTimeField(_("date joined"), default=timezone.now)

    objects = UserManager()

    EMAIL_FIELD = "email"
    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = _("user")
        verbose_name_plural = _("users")


    def clean(self):
        super().clean()
        self.email = self.__class__.objects.normalize_email(self.email)

    def get_full_name(self):
        """
        Return the first_name plus the last_name, with a space in between.
        """
        full_name = "%s" % (self.first_name)
        return full_name.strip()

    def get_short_name(self):
        """Return the short name for the user."""
        return self.first_name

    def email_user(self, subject, message, from_email=None, **kwargs):
        """Send an email to this user."""
        send_mail(subject, message, from_email, [self.email], **kwargs)

pypro/aperitivos/views.py
from django.shortcuts import render

def video(request, slug):
    return render(request, 'aperitivos/video.html')

pypro/base/views.py
from django.http import HttpResponse

from django.shortcuts import render


# Create your views here.

def home(request):
    return render(request, 'base/home.html')

pypro/aperitivos/templates/aperitivos/video.html
<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Python Pro</title>

    <meta name="description" content="Página do curso Python Pro">
    <meta name="author" content="Ryan Araújo">
	<link rel="icon" type="image/png" href="static/img/favicon.png" />

    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
    <link href="/static/css/style.css" rel="stylesheet">
    <script src="/static/js/jquery.min.js"></script>
    <script src="/static/js/bootstrap.min.js"></script>
    <script src="/static/js/scripts.js"></script>
  </head>
  <body>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="{% url 'base:home' %}">Python Pro</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#conteudoNavbarSuportado" aria-controls="conteudoNavbarSuportado" aria-expanded="false" aria-label="Alterna navegação">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="conteudoNavbarSuportado">
    <ul class="navbar-nav mr-auto">
    </ul>
  </div>
</nav>

    <div class="container">
	<div class="row">
		<div class="col-md-12">
           <div class="mt-4 mb-3">
            <h1>Video Aperitivo: Motivação</h1>
            <div style="padding:56.25% 0 0 0;position:relative;"><iframe src="https://player.vimeo.com/video/810952541?h=8966e0f115&amp;badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=58479"
                    frameborder="0" allow="autoplay; fullscreen; picture-in-picture"
                    allowfullscreen style="position:absolute;top:0;left:0;width:100%;height:100%;"
                    title="SaveTube.App-Aula 01 - MOTIVA&amp;Ccedil;&amp;Atilde;O &amp;mdash; Curso de PYTHON GR&amp;Aacute;TIS(720p).mp4"></iframe></div><script
                    src="https://player.vimeo.com/api/player.js"></script>
           </div>



		</div>
		</div>
	</div>
    <footer class="main-footer mt-5 pt-4 text-light">
        <div class="container">
            <div class="row">
                <div class="col">
                    <h3>Entre em contato</h3>
                    <address>
                        +55 12 997-411-854
                        <br/>
                        <a href="mailto:ramalho@python.pro.br" class="text-light">ramalho@python.pro.br</a>
                    </address>
                </div>
            </div>
        </div>
       <div class="rights pb-4">
        <div class="container">
            <div class="row">
                <div class="col">
                    {% now 'Y' %} Python Pro. Todos direitos reservados.
                </div>
            </div>
        </div>
       </div>
    </footer>
  </body>
</html>

pypro/base/templates/base/home.html
<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Python Pro</title>

    <meta name="description" content="Página do curso Python Pro">
    <meta name="author" content="Ryan Araújo">
	<link rel="icon" type="image/png" href="static/img/favicon.png" />

    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
    <link href="/static/css/style.css" rel="stylesheet">
    <script src="/static/js/jquery.min.js"></script>
    <script src="/static/js/bootstrap.min.js"></script>
    <script src="/static/js/scripts.js"></script>
  </head>
  <body>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="{% url 'base:home' %}">Python Pro</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#conteudoNavbarSuportado" aria-controls="conteudoNavbarSuportado" aria-expanded="false" aria-label="Alterna navegação">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="conteudoNavbarSuportado">
    <ul class="navbar-nav mr-auto">
    </ul>
  </div>
</nav>

    <div class="container">
	<div class="row">
		<div class="col-md-12">
			<div class="jumbotron">
				<h2>
					Curso de Python com Luciano Ramalho
				</h2>

				<h4 class="mt-4">Matrículas abertas! Custo R$ 1000,00</h4>
				<!-- INICIO DO BOTAO PAGSEGURO --><a href="https://pag.ae/7Zef-yMcM/button"
													 target="_blank" title="Pagar com PagSeguro"><img
											         src="//assets.pagseguro.com.br/ps-integration-assets/botoes/pagamentos/205x30-pagar.gif"
													 alt="Pague com PagSeguro - é rápido, grátis e seguro!" /></a><!-- FIM DO BOTAO PAGSEGURO -->




	<!-- 			<h4 class="mt-4">Entre na fila de espera</h4>

				<form action="https://dev.us14.list-manage.com/subscribe/post?u=ec9f105140590f8544c5793cf&amp;id=c0e6fbe1eb&amp;f_id=004d95e0f0"
					  method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form"
                      class="form-row align-items-center" target="_blank"
                      novalidate>
                    <div class="form-row align-items-center">
                        <div class="col-auto float-start me-3">
                            <label class="sr-only" for="mce-EMAIL"></label>
                            <input type="email" value="" name="EMAIL" class="form-control required" id="mce-EMAIL"
                                   placeholder="exemplo@email.com">
                        </div>
                         <div class="col-auto float-start me-3">
                             <label class="sr-only" for="mce-FNAME"></label>
                             <input type="text" value="" name="FNAME" class="form-control" id="mce-FNAME"
                                    placeholder="Seu Nome">
                         </div>

                         <!-TIRAR DPS- real people should not fill this in and expect good things - do not remove this or risk form bot signups-TIRAR DEPOIS->
                         <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text"
                                                                                                   name="b_ec9f105140590f8544c5793cf_c0e6fbe1eb"
                                                                                                   tabindex="-1"
                                                                                                   value=""></div>
	 					<div class="col-auto">
                             <input type="submit" value="Salvar" name="subscribe"
                                    {# id="mc-embedded-subscribe" class="btn btn-primary">
                         </div>
                     </div>
                 </form>-->

            </div>
		</div>
			<div class="row">
				<div class="col-md-12">
					<div class="card mt-5">
						<h5 class="card-header">
								Mais detalhes sobre o instrutor
						</h5>
						<div class="card-body">
							<p class="card-text">
								<img src="static/img/luciano-ramalho.png" alt="Foto de Luciano Ramalho"
									 class="img-thumbnail float-left mr-2"/>
								Ramalho é sócio e professor na <a href="www.python.pro.br">Python Pro</a> e autor do Livro
								<a href="http://shop.oreilly.com/product/0636920032519.do" target="_blank" >Python Fluente</a>. Foi diretor técnico do Brasil Online, primeiro portal da Abril S/A na Web.
								Liderou times para os portais IDG Now, BOL, UOL, AOL Brasil e outros, usando Python desde 1998.
								Como instrutor, atendeu clientes como Citibank, CPqD, Serpro, Presidência da República,
								Globo.com e Itaú. Palestrante em eventos internacionais como FISL, PyCon US e OSCON. Ajudou a
								criar a Associação Python Brasil e foi seu presidente. É membro da Python Software Foundation e
								fundador da Garoa Hacker Clube, o primeiro hackerspace do Brasil.
							</p>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
<footer class="main-footer mt-5 pt-4 text-light">
	<div class="container">
		<div class="row">
			<div class="col">
				<h3>Entre em contato</h3>
				<address>
					+55 12 997-411-854
					<br/>
					<a href="mailto:ramalho@python.pro.br" class="text-light">ramalho@python.pro.br</a>
				</address>
			</div>
		</div>
	</div>
   <div class="rights pb-4">
	<div class="container">
		<div class="row">
			<div class="col">
				{% now 'Y' %} Python Pro. Todos direitos reservados.
			</div>
		</div>
	</div>
   </div>
</footer>
  </body>
</html>